Web/Areas/GiaoVien/Controllers/BaoCaoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Web.Models;
using PagedList;


namespace Web.Areas.GiaoVien.Controllers
{
    public class BaoCaoController : Controller
    {
        private WebMVCEntities db = new WebMVCEntities();

        // GET: GiaoVien/BaoCao
        public ActionResult Index(int Page=1, int PageSize=8)
        {
            var baoCaos = db.BaoCaos.Include(b => b.Nhom);
            var baoCaos1 = baoCaos.OrderBy(p => p.Tuan).ToPagedList(Page, PageSize);
            return View(baoCaos1);
        }

        // GET: GiaoVien/BaoCao/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BaoCao baoCao = await db.BaoCaos.FindAsync(id);
            if (baoCao == null)
            {
                return HttpNotFound();
            }
            return View(baoCao);
        }
        public async Task<ActionResult> Feedback(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BaoCao baoCao = await db.BaoCaos.FindAsync(id);
            if (baoCao == null)
            {
                return HttpNotFound();
            }
            ViewBag.Nhom_ID = new SelectList(db.Nhoms, "ID", "TenNhom", baoCao.Nhom_ID);
            return View(baoCao);
        }

        // POST: GiaoVien/BaoCaos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Feedback(BaoCao baoCao)
        {
            if (ModelState.IsValid)
            {
                db.Entry(baoCao).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.Nhom_ID = new SelectList(db.Nhoms, "ID", "TenNhom", baoCao.Nhom_ID);
            return View(baoCao);
        }



        // GET: GiaoVien/BaoCao/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BaoCao baoCao = await db.BaoCaos.FindAsync(id);
            if (baoCao == null)
            {
                return HttpNotFound();
            }
            return View(baoCao);
        }

        // POST: GiaoVien/BaoCao/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            BaoCao baoCao = await db.BaoCaos.FindAsync(id);
            db.BaoCaos.Remove(baoCao);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Web/Areas/GiaoVien/Controllers/DeTaiController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Web.Models;
using PagedList.Mvc;
using PagedList;

namespace Web.Areas.GiaoVien.Controllers
{
    public class DeTaiController : Controller
    {
        private WebMVCEntities db = new WebMVCEntities();

        // GET: GiaoVien/DeTai
        public ActionResult Index(int Page = 1, int PageSize = 8)
        {
            var deTai1 = db.DeTais.OrderBy(p => p.ID).ToPagedList(Page, PageSize);
            return View(deTai1);
        }

        // GET: GiaoVien/DeTai/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DeTai deTai = await db.DeTais.FindAsync(id);
            if (deTai == null)
            {
                return HttpNotFound();
            }
            return View(deTai);
        }

        // GET: GiaoVien/DeTai/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: GiaoVien/DeTai/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "ID,TenDeTai,YeuCauDeTai,ThoiGianBatDau,ThoiGianKetThuc,SoTuanThucHien")] DeTai deTai)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    db.DeTais.Add(deTai);
                    await db.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
                catch
                {
                    ViewBag.Alert = "Tên đề tài không được trùng nhau và thời gian bắt đầu phải nhỏ hơn thời gian kết thúc. Mời nhập lại!";
                }
            }



            return View(deTai);
        }

        // GET: GiaoVien/DeTai/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DeTai deTai = await db.DeTais.FindAsync(id);
            if (deTai == null)
            {
                return HttpNotFound();
            }
            return View(deTai);
        }

        // POST: GiaoVien/DeTai/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "ID,TenDeTai,YeuCauDeTai,ThoiGianBatDau,ThoiGianKetThuc,SoTuanThucHien")] DeTai deTai)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    db.Entry(deTai).State = EntityState.Modified;
                    await db.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
                catch
                {
                    ViewBag.Alert = "Tên đề tài không được trùng nhau và thời gian bắt đầu phải nhỏ hơn thời gian kết thúc. Mời nhập lại!";
                }
            }
            return View(deTai);
        }

        // GET: GiaoVien/DeTai/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DeTai deTai = await db.DeTais.FindAsync(id);
            if (deTai == null)
            {
                return HttpNotFound();
            }
            return View(deTai);
        }

        // POST: GiaoVien/DeTai/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            DeTai deTai = await db.DeTais.FindAsync(id);
            db.DeTais.Remove(deTai);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Web/Areas/GiaoVien/Controllers/TrangChuController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Web.Models;
using Web.Common;
using PagedList;

namespace Web.Areas.GiaoVien.Controllers
{
    public class TrangChuController : Controller
    {
        private WebMVCEntities db = new WebMVCEntities();

        public ActionResult Logout()
        {
            Session[CommonConstants.USER_SESSION] = null;
            return RedirectToAction("Login", "Login", new { area = "" });
        }
        public ActionResult Index(string searchString, int Page=1, int PageSize=8)
        {
            var nguoiDungs = db.NguoiDungs.Include(n => n.ChucVu).Include(n => n.DeTai).Include(n => n.Nhom);
            if (!string.IsNullOrEmpty(searchString))
            {
                nguoiDungs =nguoiDungs.Where(x => x.HoTen.Contains(searchString));
                
            }
            ViewBag.SearchString = searchString;
            var nguoiDung = nguoiDungs.OrderBy(p => p.Nhom_ID).ToPagedList(Page, PageSize);
            return View(nguoiDung);
        }

        // GET: GiaoVien/TrangChu/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NguoiDung nguoiDung = await db.NguoiDungs.FindAsync(id);
            if (nguoiDung == null)
            {
                return HttpNotFound();
            }
            return View(nguoiDung);
        }

        // GET: GiaoVien/TrangChu/Create
        public ActionResult Create()
        {
            ViewBag.ChucVu_ID = new SelectList(db.ChucVus, "ID", "TenChucVu");
            ViewBag.DeTai_ID = new SelectList(db.DeTais, "ID", "TenDeTai");
            ViewBag.Nhom_ID = new SelectList(db.Nhoms, "ID", "TenNhom");
            return View();
        }

        // POST: GiaoVien/TrangChu/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "ID,TenDangNhap,MatKhau,HoTen,Email,Nhom_ID,DeTai_ID,ChucVu_ID")] NguoiDung nguoiDung)
        {
            if (ModelState.IsValid)
            {
                nguoiDung.MatKhau = Encryptor.MD5Hash(nguoiDung.MatKhau);
                db.NguoiDungs.Add(nguoiDung);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.ChucVu_ID = new SelectList(db.ChucVus, "ID", "TenChucVu", nguoiDung.ChucVu_ID);
            ViewBag.DeTai_ID = new SelectList(db.DeTais, "ID", "TenDeTai", nguoiDung.DeTai_ID);
            ViewBag.Nhom_ID = new SelectList(db.Nhoms, "ID", "TenNhom", nguoiDung.Nhom_ID);
            return View(nguoiDung);
        }

        //// GET: GiaoVien/TrangChu/Edit/5
        //public async Task<ActionResult> Edit(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    NguoiDung nguoiDung = await db.NguoiDungs.FindAsync(id);
        //    if (nguoiDung == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    ViewBag.ChucVu_ID = new SelectList(db.ChucVus, "ID", "TenChucVu", nguoiDung.ChucVu_ID);
        //    ViewBag.DeTai_ID = new SelectList(db.DeTais, "ID", "TenDeTai", nguoiDung.DeTai_ID);
        //    ViewBag.Nhom_ID = new SelectList(db.Nhoms, "ID", "TenNhom", nguoiDung.Nhom_ID);
        //    return View(nguoiDung);
        //}

        //// POST: GiaoVien/TrangChu/Edit/5
        //// To protect from overposting attacks, enable the specific properties you want to bind to, for 
        //// more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit([Bind(Include = "ID,TenDangNhap,MatKhau,HoTen,Email,Nhom_ID,DeTai_ID,ChucVu_ID")] NguoiDung nguoiDung)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Entry(nguoiDung).State = EntityState.Modified;
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //    ViewBag.ChucVu_ID = new SelectList(db.ChucVus, "ID", "TenChucVu", nguoiDung.ChucVu_ID);
        //    ViewBag.DeTai_ID = new SelectList(db.DeTais, "ID", "TenDeTai", nguoiDung.DeTai_ID);
        //    ViewBag.Nhom_ID = new SelectList(db.Nhoms, "ID", "TenNhom", nguoiDung.Nhom_ID);
        //    return View(nguoiDung);
        //}

        // GET: GiaoVien/TrangChu/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NguoiDung nguoiDung = await db.NguoiDungs.FindAsync(id);
            if (nguoiDung == null)
            {
                return HttpNotFound();
            }
            return View(nguoiDung);
        }

        // POST: GiaoVien/TrangChu/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            NguoiDung nguoiDung = await db.NguoiDungs.FindAsync(id);
            db.NguoiDungs.Remove(nguoiDung);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Web/Areas/SinhVien/Views/Shared/_Layout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Đồ án CNTT-@ViewBag.Title</title>

    <!-- Custom fonts for this template-->
    <link href="~/Assets/GiaoVien/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="~/Assets/GiaoVien/css/sb-admin-2.min.css" rel="stylesheet">

</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="@Url.Action("Index","TrangChu")">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-laugh-wink"></i>
                </div>
                <div class="sidebar-brand-text mx-3">Sinh Viên</div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item active">
                <a class="nav-link" href="@Url.Action("Index","TrangChu")">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Trang chủ</span>
                </a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <div class="nav-item">
                <a class="nav-link collapsed" href="@Url.Action("Index","DeTai")">
                    <i class="fas fa-fw fa-cog"></i>
                    <span>Đề tài</span>
                </a>
            </div>


            <!-- Nav Item - Utilities Collapse Menu -->
            <div class="nav-item">
                <a class="nav-link collapsed" href="@Url.Action("Index","BaoCao")">
                    <i class="fas fa-fw fa-wrench"></i>
                    <span>Báo cáo</span>
                </a>
            </div>


            <div class="nav-item">
                <a class="nav-link collapsed" href="@Url.Action("Feedback","BaoCao")">
                    <i class="fas fa-bell fa-fw"></i>
                    <span>Phản hồi</span>
                </a>
            </div>

            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">

            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>



        </ul>

        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">


                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                    <!-- Topbar Search -->
                    <!--<form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
                        <div class="input-group">
                            <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..."
                                   aria-label="Search" aria-describedby="basic-addon2">
                            <div class="input-group-append">
                                <button class="btn btn-primary" type="button">
                                    <i class="fas fa-search fa-sm"></i>
                                </button>
                            </div>
                        </div>
                    </form>-->

                    <!-- Topbar Navbar -->
                    <div class="navbar-nav ml-auto">


                        @{
                            var session = (Web.Common.UserLogin)Session[Web.Common.CommonConstants.USER_SESSION];
                        }
                        <!-- Nav Item - User Information -->
                        <div class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">@session.HoTen</span>
                                <img class="img-profile rounded-circle"
                                     src="~/Assets/GiaoVien/img/undraw_profile.svg">
                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                 aria-labelledby="userDropdown">
                                <a class="dropdown-item" href="@Url.Action("Logout","TrangChu")">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Logout
                                </a>


                            </div>
                        </div>

                    </div>

                </nav>
                <div class="container-fluid">

                    @RenderBody()
                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->
            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Your Website 2020</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="login.html">Logout</a>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="~/Assets/GiaoVien/vendor/jquery/jquery.min.js"></script>
    <script src="~/Assets/GiaoVien/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="~/Assets/GiaoVien/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="~/Assets/GiaoVien/js/sb-admin-2.min.js"></script>

    <!-- Page level plugins -->
    <script src="~/Assets/GiaoVien/vendor/chart.js/Chart.min.js"></script>

    <!-- Page level custom scripts -->
    <script src="~/Assets/GiaoVien/js/demo/chart-area-demo.js"></script>
    <script src="~/Assets/GiaoVien/js/demo/chart-pie-demo.js"></script>

</body>

</html>